application: {{ project_name }}
version: local
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: PIL
  version: "1.1.7"

env_variables:
  DJANGO_SETTINGS_MODULE: '{{ project_name }}.settings'

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  expiration: '7d'
  secure: always
  http_headers:
    X-Frame-Options: "DENY"
    Strict-Transport-Security: "max-age=2592000; includeSubdomains"
    X-Content-Type-Options: "nosniff"
    X-XSS-Protection: "1; mode=block"

- url: /static
  static_dir: static
  expiration: '14d'
  secure: always
  http_headers:
    X-Frame-Options: "DENY"
    Strict-Transport-Security: "max-age=2592000; includeSubdomains"
    X-Content-Type-Options: "nosniff"
    X-XSS-Protection: "1; mode=block"
    Vary: Accept-Encoding

- url: /.*
  secure: always
  script: {{ project_name }}.wsgi.application

skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$

pagespeed:
 enabled_rewriters:

 # These are enabled by default, but better to explictiy set
  - ProxyCss
  - ProxyImages
  - ProxyJs
  - ConvertMetaTags
  - CombineCss
  - CombineJs
  - JsOptimize
  # .. bunch of image optims

# Optional
  - InlineJs
  - CollapseWhitespace
  - CombineHeads
  - RemoveComments
  - RemoveQuotes
  - LeftTrimUrls
  - MinifyCss

 disabled_rewriters:
  - MoveCssToHead
  - InlineCss
  - InlinePreviewImages
  - LazyloadImages
  - ElideAttributes
